name: calendar_example
description: Demonstrates how to use the nepali calendar bs ad plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bs_ad_calendar:
    path: ../
  intl: ^0.19.0
  nepali_utils: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true